### ISSUE TITLE
NotFine crash in GTNH 2.4.0

### ISSUE THREAD

**Issue by autumn-2-net** [jss2a98aj/NotFine#12]
this is log 
[minecraft-exported-logs-2023-10-31T18-46-29.log](https://github.com/jss2a98aj/NotFine/files/13215472/minecraft-exported-logs-2023-10-31T18-46-29.log)

**Comment by autumn-2-net** [comment]
![图片](https://github.com/jss2a98aj/NotFine/assets/109412646/4c979fcf-e9de-4986-b025-a98ed0da045e)
now i have other pobelm  when i open this 
![图片](https://github.com/jss2a98aj/NotFine/assets/109412646/5b957449-c3c3-47da-8911-3fd112299f2e)
the game black

**Comment by jss2a98aj** [comment]
That is just the end of the log file and only contains a small amount of information.
It looks like Angelica is being used. Angelica is not complete yet, but it will include NotFine in the future.
