### ISSUE TITLE
Feature request (VSync)

### ISSUE THREAD

**Issue by mts2200** [jss2a98aj/NotFine#15]
When u play with optifine, u can use VSync for frame-rate. I think this is a useful option so that the frame rate in the game always matches your monitor hz.
![image](https://github.com/jss2a98aj/NotFine/assets/82391229/bf8a2c4b-ce41-489c-be77-fabee12aeac5)

**Comment by jss2a98aj** [comment]
Vanilla Minecraft and by extension NotFine has an option for VSync, it just isn't merged into the max framerate slider.

**Comment by mts2200** [comment]
Are you planning to merge this? How to enable VSync now? I didn't find an option for this.

**Comment by jss2a98aj** [comment]
VSync can be enabled by setting "Use VSync" to on. It is directly above the framerate slider with the menu layout NotFine uses.

**Comment by mts2200** [comment]
Uh, I find it, thx. In my language, the setting was called differently and I did not pay attention to it.
