### ISSUE TITLE
FalseTweaks multithreaded chunk rendering causes snow layers to flicker

### ISSUE THREAD

**Issue by Omgise** [jss2a98aj/NotFine#16]
See details: https://github.com/FalsePattern/FalseTweaks/issues/149

**Comment by jss2a98aj** [comment]
This is not something that can be properly fixed in NotFine. I can turn off some functionality to work around it though. For the moment rolling back to 0.1.0 will have the same result as the workaround.

**Comment by jss2a98aj** [comment]
False has said that he ported over the minmax threading fix from Angelica to Falsetweaks in https://github.com/FalsePattern/FalseTweaks/issues/149 discussion, and that it will be included in its next update.
