### ISSUE TITLE
Notfine breaks enchantment glinted items in GTNH NEI fork when caching is enabled

### ISSUE THREAD

**Issue by Polarite** [jss2a98aj/NotFine#2]
title explains all

**Comment by jss2a98aj** [comment]
It may also break with upstream BugTorch on default settings as I have modified the same class in it. I will see what I can do.

**Comment by jss2a98aj** [comment]
A fix has been committed and will be included in alpha 16

**Comment by jss2a98aj** [comment]
The problem still occurs in some situations, issue reopened.

**Comment by jss2a98aj** [comment]
Should actually be fixed now
