### ISSUE TITLE
Minor feature requests

### ISSUE THREAD

**Issue by eigenraven** [jss2a98aj/NotFine#3]
I decided to test this in gtnh, here are some minor enhancements that would be nice-to-have:
 
- [x] Support refresh rate of 144Hz (75, 165 Hz are the other common non-10-divisible frequencies) in the slider
- [x] GUI Scale slider could support bigger scales than Large (probably 1 up from that is enough)

**Comment by jss2a98aj** [comment]
Good to know it works in GTNH, I hadn't gotten around to extensive testing with other mods yet. I will see about adding those features soon.

**Comment by jss2a98aj** [comment]
Both features are now present in alpha 18
