### ISSUE TITLE
Crash when searching "an" in the creative menu

### ISSUE THREAD

**Issue by Midnight145** [jss2a98aj/NotFine#48]
Seemingly crashes when it tries to render the anvil texture in the search results.

Unimixins 0.1.19
NotFine 0.2.5
No other mods

[crash-2024-12-02_17.45.47-client.txt](https://github.com/user-attachments/files/17985110/crash-2024-12-02_17.45.47-client.txt)

**Comment by Midnight145** [comment]
ah, looks like duplicate of #36, feel free to close

**Comment by unicornbloods** [comment]
Duplicate of [36](https://github.com/jss2a98aj/NotFine/issues/36)
