### ISSUE TITLE
Where is the config file?

### ISSUE THREAD

**Issue by quentin452** [jss2a98aj/NotFine#9]
Because i want to disabling World Enchant Glint VFX in my modpack , because itemframes with potions make the fps extreme lag in my modpack , but idk where is the config file to upload it to my modpack

**Comment by jss2a98aj** [comment]
The user selected option file is at "root/optionsGraphics.cfg" and the config is at "root\config\notfine\notfine.cfg"

**Comment by quentin452** [comment]
ok thx
